version: "3.7"

services:

  bitcoind:
    image: "${APP_BITCOIND_IMAGE}"
    restart: unless-stopped
    stop_grace_period: 15m30s
    volumes:
      - "${NODE_DATA_DIR}/bitcoind/data/bitcoin:/data/.bitcoin"
    networks:
      bitcoin:
    command:
      - "-debug=rpc"
      - "-txindex"
      - "-rpcbind=0.0.0.0"
      - "-rpcallowip=127.0.0.1"
      - "-rpcallowip=${NODE_BITCOIN_NETWORK}"
      - "-rpcauth=${APP_BITCOIND_USER_RPCAUTH}"
      - "-rpcauth=${APP_BITCOIND_MEMPOOL_RPCAUTH}"
