version: "3.7"

services:

  bitcoind:
    image: "${APP_BITCOIN_IMAGE}"
    restart: unless-stopped
    stop_grace_period: 15m30s
    volumes:
      - "${NODE_DATA_DIR}/bitcoind/data/bitcoin:/data/.bitcoin"
    ports:
      - "127.0.0.1:8332:8332"
    networks:
      bitcoin:
        ipv4_address: ${APP_BITCOIN_IP}
    command:
      - "-debug=rpc"
      - "-txindex"
      - "-rpcbind=127.0.0.1"
      - "-rpcallowip=127.0.0.1"
      - "-rpcbind=${APP_BITCOIN_IP}"
      - "-rpcallowip=${NODE_BITCOIN_NETWORK}"
      - "-rpcauth=${APP_BITCOIND_USER_RPCAUTH}"
      - "-rpcauth=${APP_BITCOIND_MEMPOOL_RPCAUTH}"
