version: "3.7"

services:

  haproxy:
    image: "${NODE_HAPROXY_IMAGE}"
    environment:
      NODE_HAPROXY_IP: ${NODE_HAPROXY_IP}
      APP_BITCOIND_IP: ${APP_BITCOIND_IP}
      APP_BITCOIND_RPC_PORT: 8332
      NODE_BITCOIND_RPC_PORT: ${NODE_BITCOIND_RPC_PORT}
    networks:
      default:
        ipv4_address: ${NODE_HAPROXY_IP}
      bitcoin:
      mempool:
    ports:
      - "${NODE_BITCOIND_RPC_IP}:${NODE_BITCOIND_RPC_PORT}:${NODE_BITCOIND_RPC_PORT}"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
