version: "3.7"

networks:
  # port bindings happen on the first network alphabetical order
  # HAProxy connects to all networks but binds only on the proxynet
  a0_proxynet:
    ipam:
      config:
        - subnet: "${NODE_DEFAULT_NETWORK}"
  bitcoin:
    ipam:
      config:
        - subnet: "${NODE_BITCOIN_NETWORK}"
  mempool:
    ipam:
      config:
        - subnet: "${NODE_MEMPOOL_NETWORK}"