version: "3.7"

networks:
  default:
    ipam:
      config:
        - subnet: "${NODE_DEFAULT_NETWORK}"
  bitcoin:
    ipam:
      config:
        - subnet: "${NODE_BITCOIN_NETWORK}"
  mempool:
    ipam:
      config:
        - subnet: "${NODE_MEMPOOL_NETWORK}"