version: "3.7"

networks:
  # port bindings happen on the first network alphabetical order
  # HAProxy connects to all networks but binds only on the external network
  a0_external:
    ipam:
      config:
        - subnet: "${NODE_EXTERNAL_NETWORK}"
  bitcoin:
    ipam:
      config:
        - subnet: "${NODE_BITCOIN_NETWORK}"
  mempool:
    ipam:
      config:
        - subnet: "${NODE_MEMPOOL_NETWORK}"
  electrum:
    ipam:
      config:
        - subnet: "${NODE_ELECTRS_NETWORK}"