version: "3.7"

services:

  mempool-frontend:
    depends_on:
      - mempool-backend
      - mempool-db
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: ${APP_MEMPOOL_FRONTEND_IMAGE}
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15s
    command: "./wait-for mempool-db:3306 --timeout=30 -- nginx -g 'daemon off;'"
    ports:
      - 9080:8080
    networks:
      - mempool

  mempool-backend:
    depends_on:
      - bitcoind
      - mempool-db
    environment:
      MEMPOOL_BACKEND: "none"
      CORE_RPC_HOST: "${APP_BITCOIND_IP}"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "mempool"
      CORE_RPC_PASSWORD: "${APP_MEMPOOL_BITCOIND_PASSWORD}"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "${APP_MEMPOOL_MYSQL_PASSWORD}"
      STATISTICS_ENABLED: "true"
    image: ${APP_MEMPOOL_BACKEND_IMAGE}
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15s
    command: "./wait-for-it.sh mempool-db:3306 --timeout=30 --strict -- ./start.sh"
    volumes:
      - ${NODE_DATA_DIR}/mempool/data/backend:/backend/cache
    networks:
      - bitcoin
      - mempool

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "${APP_MEMPOOL_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${APP_MEMPOOL_MYSQL_ROOT_PASSWORD}"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${NODE_DATA_DIR}/mempool/data/mysql:/var/lib/mysql
    networks:
      - mempool

networks:
  mempool:
    ipam:
      config:
        - subnet: ${NODE_MEMPOOL_NETWORK}
